import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserratBlack = Montserrat({
  weight: "900",
  subsets: ["latin"],
  variable: "--font-montserrat-black",
});

const montserratNormal = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat-normal",
});

export const metadata: Metadata = {
  title: "Tune In",
  description: "Generated by Manjencici",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratBlack.variable} ${montserratNormal.variable} antialiased`}
      > 
        <Navbar />
        {children}
      </body>
    </html>
  );
}